#!/usr/bin/env bash
# Redirect
apt update -y
apt install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-devian.html
sed -i '/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start