#!/usr/bin/env bash
# Find out what’s keeping your Ubuntu container’s Nginx installation 
# from listening on port 80. Feel free to install whatever tool you need,
# start and destroy as many containers as you need to debug the issue.

sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx start
pkill nginx
sudo service nginx restart