#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s
# Nginx installation from listening on port 80
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /usr/share/nginx/html;
        index index.html index.htm;

        server_name localhost;

        location / {
                try_files $uri $uri/ =404;
        }
}" > /etc/nginx/sites-enabled/default
pkill nginx
sudo service nginx start
