#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s
# Nginx installation from listening on port 80
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo pkill -o nginx
