#!/usr/bin/env bash
# Process and PID file "Why you no love me??"
NAME="To infinity and beyond"
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "sudo rm -f /var/run/holbertonscript.pid; exit" SIGQUIT
touch /var/run/holbertonscript.pid
while true; do
    echo "$NAME"
    sleep 2
done
