#!/usr/bin/env bash
# Process and PID file "Why you no love me??"
NAME="To infinity and beyond"
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
echo $$ > /var/run/holbertonscript.pid
while true; do
    echo "$NAME"
    sleep 2
done
