#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user,
# short and sweet.

chmod 777 /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start